version: '3'

services:
  apache:
    container_name: symfony-api
    image: php:8.2-apache
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/
      - ./public:/var/www/html/
    
  php:
    container_name: php82
    image: php:8.2-fpm-alpine3.17